class SemanticCube:
  def __init__(self):
    self.cube={
      "entero":{
        "entero":{
          "+":"entero",
          "-":"entero",
          "*":"entero",
          "/":"decimal",
          ">":"booleano",
          "<":"booleano",
          "==":"booleano",
          ">=":"booleano",
          "<=":"booleano",
          "<>":"booleano",
          "=":"entero"
        },
        "decimal":{
          "+":"decimal",
          "-":"decimal",
          "*":"decimal",
          "/":"decimal",
          ">":"booleano",
          "<":"booleano",
          "==":"booleano",
          ">=":"booleano",
          "<=":"booleano",
          "<>":"booleano",
          "=":"ERROR"
        },
        "booleano":{
          "+":"ERROR",
          "-":"ERROR",
          "*":"ERROR",
          "/":"ERROR",
          ">":"ERROR",
          "<":"ERROR",
          "==":"ERROR",
          ">=":"ERROR",
          "<=":"ERROR",
          "<>":"ERROR",
          "=":"ERROR"
        }
      },
      "decimal":{
        "entero":{
          "+":"decimal",
          "-":"decimal",
          "*":"decimal",
          "/":"decimal",
          ">":"booleano",
          "<":"booleano",
          "==":"booleano",
          ">=":"booleano",
          "<=":"booleano",
          "<>":"booleano",
          "=":"decimal"
        },
        "decimal":{
          "+":"decimal",
          "-":"decimal",
          "*":"decimal",
          "/":"decimal",
          ">":"booleano",
          "<":"booleano",
          "==":"booleano",
          ">=":"booleano",
          "<=":"booleano",
          "<>":"booleano",
          "=":"decimal"
        },
        "booleano":{
          "+":"ERROR",
          "-":"ERROR",
          "*":"ERROR",
          "/":"ERROR",
          ">":"ERROR",
          "<":"ERROR",
          "==":"ERROR",
          ">=":"ERROR",
          "<=":"ERROR",
          "<>":"ERROR",
          "=":"ERROR"
        }
      },
      "booleano":{
        "entero":{
          "+":"ERROR",
          "-":"ERROR",
          "*":"ERROR",
          "/":"ERROR",
          ">":"ERROR",
          "<":"ERROR",
          "==":"ERROR",
          ">=":"ERROR",
          "<=":"ERROR",
          "<>":"ERROR",
          "=":"ERROR"
        },
        "decimal":{
          "+":"ERROR",
          "-":"ERROR",
          "*":"ERROR",
          "/":"ERROR",
          ">":"ERROR",
          "<":"ERROR",
          "==":"ERROR",
          ">=":"ERROR",
          "<=":"ERROR",
          "<>":"ERROR",
          "=":"ERROR"
        },
        "booleano":{
          "+":"ERROR",
          "-":"ERROR",
          "*":"ERROR",
          "/":"ERROR",
          ">":"booleano",
          "<":"booleano",
          "==":"booleano",
          ">=":"booleano",
          "<=":"booleano",
          "<>":"booleano",
          "=":"booleano"
        }
      },
    }