programa "prueba";
var &i : entero, 
    &j : decimal, 
    &x : decimal, 
    &y : decimal;

funcion : entero ~uno(&juan : entero, &pancho : decimal){
  var &k : decimal;
  &k = 1 + 2 - -3 * (-3.0 / 4);
  si(&juan < &pancho){
    imprimir &i;
  } sino {
    imprimir &j;
  }
  regresar &juan;
}

funcion : void ~dos(&juan : entero, &pancho : decimal){
  var &k : entero;
  imprimir &k;
  imprimir (1+2-3*(4/3*4.3));
  si(&juan < &pancho){
    imprimir &i;
  } sino {
    imprimir &j;
  }
}

dibujar(){
  var &h : decimal;

  adelante 60;
  rotar &i;
  cuadrado 5, 6, 19, rgb(10,34,255), 5;
  circulo 0, 0, 10, rgb(10,34,23), 2;
  triangulo &j, 10, ~uno(&x,&y), 5, rgb(10,34,23), 2;
  texto 1, 0, 'juancho', rgb(10,34,23), 24;

  mientras(&i < 10){
    &i = &i + 1;
    ~dos(&x, 1+2-3/4*4*(4+3/3*&x));
  }

  &i = ~uno(&x, &j);
}