programa "prueba";
var &i : entero, &j : decimal;

funcion : entero ~uno(&juan : entero, &pancho : decimal){
  var &k : entero;
  &k=100;
  si(&juan < &pancho){
    imprimir &i;
  } sino {
    imprimir &j;
  }
  regresar &k;
}

dibujar(){
  var &h : decimal, &x:entero, &y:decimal;

  &x = 4;
  &y = 4.3;
  &i = 10;
  &j = 10.3;

  adelante 60;
  rotar &i;
  cuadrado 5, 6, 19, rgb(10,34,23), 5;
  circulo 0,0,10,rgb(10,34,23),2;
  triangulo &j, 10, ~uno(&x,&y),5, rgb(10,34,23), 2;
  texto 1, 0, 'juancho', rgb(10,34,23), 24;

  mientras(&i < 10){
    &i = &i + 1;
  }

  ~uno(&i, &j);
}