programa "sort";

dibujar(){
  var &lista : entero[10], &i : entero, &j:entero, &tmp:entero;

  &i=0;
  mientras(&i<10){
    leer &lista[&i];
    &i=&i+1;
  }

  &i=1;
  mientras(&i < 10){
    &j=0;
    mientras(&j < 9){
      si(&lista[&j] > &lista[&j+1]){
        &tmp = &lista[&j];
        &lista[&j] = &lista[&j+1];
        &lista[&j+1] = &tmp;
      }
      &j=&j+1;
    }
    &i=&i+1;
  }

  &i=0;
  mientras(&i < 10){
    imprimir &lista[&i];
    &i = &i +1;
  }

}
